### DISCUSSION TITLE
Adding custom hunspell dictionary

### DISCUSSION THREAD

**Discussion by tdimitrov** [streetsidesoftware/vscode-spell-checker#2653] [Q&A]
Is it still possible to add your own dictionary in hunspell format?

I found [this](https://github.com/streetsidesoftware/vscode-spell-checker/issues/1#issuecomment-272694261) discussion but the link there is now dead.

A bit more context. The project I work on uses [this dictionary](https://github.com/paritytech/polkadot/blob/5a43bc733024b6f2d4f1164db8991a393c8e14cb/scripts/ci/gitlab/lingua.dic) and I want to integrate it in my workflow.

**Comment by Jason3S** [comment]
@tdimitrov,

The dictionaries used in the spell checker are found here: https://github.com/streetsidesoftware/cspell-dicts
They use the [cspell-tools-cli](https://www.npmjs.com/package/@cspell/cspell-tools) to convert Hunspell files into a supported format.

The README for `cspell-tools` seems to be out of date. There are more options.

The easiest way to try it would be:

**`cspell-tools.config.yaml`**
```yaml
targets:
  - name: company-dictionary
    sources:
      - src/hunspell/index.aff
    format: trie3
    generateNonStrict: true
```

```sh
cspell-tools-cli build
```

The `build` command looks for a `cspell-tools.config.yaml` file and will generate a `company-dictionary.trie` file that can be used in a `cspell.config.yaml` file.

**`cspell.config.yaml`**
```yaml
dictionaryDefinitions:
  - name: company-dictionary
    path: ./company-dictionary.trie
dictionaries:
  - company-dictionary
```

**Reply by tdimitrov** [reply]
Thanks @Jason3S! I'll give it a try.

**Comment by tdimitrov** [comment]
My input is [`.dic`](https://github.com/paritytech/polkadot/blob/5a43bc733024b6f2d4f1164db8991a393c8e14cb/scripts/ci/gitlab/lingua.dic) file so I created:
```
targets:
  - name: polkadot
    sources:
      - lingua.dic
    format: trie3
    generateNonStrict: true
```
and it yields:
```
$ cspell-tools-cli build
2023-05-22T17:27:43.312Z Start compile: polkadot
2023-05-22T17:27:43.314Z Reading lingua.dic
[Error: ENOENT: no such file or directory, open '/work/lingua.aff'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/work/lingua.aff'
}
```
`/work` is my CWD, but I've got no `lingua.aff` file.

Also if this step succeeds what should I do with the `cspell.config.yaml` file?
