### DISCUSSION TITLE
Mismatch in installed dictionaries?

### DISCUSSION THREAD

**Discussion by adam-moss** [streetsidesoftware/vscode-spell-checker#3370] [Q&A] [answered]
Hi

I've been using the vs-code extension for some time now and have today been looking at integrating the cspell-cli into our pre-commit hooks in replacement of codespell.

One thing I've noticed is that with a clean install of both there are differences in the bundled dicts.

E.g. when scanning the `.pre-commit-config.yaml` file itself the vscode plugin reports 1 additional error, the word linebreak from the following:

```yaml
      - id: trailing-whitespace
        stages:
          - pre-commit
        args:
          - --markdown-linebreak-ext=md
```

Running `cspell trace linebreak` shows this is defined in `dict-software-terms`.

Looking at the `package.json` of `dict-software-terms` shows:

vscode
> "name": "@cspell/dict-software-terms", "version": "3.2.3",

pre-commit
> "name": "@cspell/dict-software-terms", "version": "3.3.23",

Is there any way to ensure these are updated / aligned?

Thanks!
