### ISSUE TITLE
r

### ISSUE THREAD

**Issue by aradalvand** [streetsidesoftware/vscode-spell-checker#2365]

**Comment by Jason3S** [comment]
@aradalvand,

At the moment, the spell checker treats `.svelte` file like any other text file.

I'll update the `cspell` library to be aware of Svelte files. In the meantime, you can tell the spell checker how to handle them.

## Use a `cspell.config.yaml` file

**`cspell.config.yaml`**
```yaml
languageSettings:
  - caseSensitive: false
    languageId: svelte
    dictionaries: ['typescript', 'npm', 'html', 'html-symbol-entities', 'css', 'fonts']
overrides:
  - filename: '**/*.svelte'
    languageId: svelte
```

## Using VS Code Settings:

<img width="496" alt="image" src="https://user-images.githubusercontent.com/3740137/204319676-ea10bcb5-7959-43a5-84e8-ac747064dfc8.png">

**`.vscode/settings.json`**
```json
    "cSpell.languageSettings": [
        {
            "languageId": "svelte",
            "dictionaries": ["typescript", "npm", "html", "html-symbol-entities", "css", "fonts"]
        }
    ]
```
