### ISSUE TITLE
Disable language checking

### ISSUE THREAD

**Issue by brendan8c** [streetsidesoftware/vscode-spell-checker#2427]
How can I turn off the English language check?
I don't like that it underlines words in my code. 
I don't need him to check my code!
If this is already implemented, please write the code for my settings.json file.

**Comment by Jason3S** [comment]
@brendan8c,

It is possible to disable the spell checker for each file type.

Using a command:
<img width="622" alt="image" src="https://user-images.githubusercontent.com/3740137/210948106-7fdaae83-2a59-48c3-9bda-fc9b69078e04.png">

**Comment by brendan8c** [comment]
Is there a setting for the settings.json file?

**Comment by brendan8c** [comment]
It is not comfortable! What will happen if each plugin requires you to enter a command to run a particular function?
It is much more convenient to create settings for all plugins in the settings.json file and forget about the settings.
For this reason, I am against any teams.
I will be glad if you provide settings for the settings.json file

**Comment by Jason3S** [comment]
@brendan8c,

It is a setting, but most people do not find them. Running the command should have updated your `setting.json` file.

**`settings.json`**
```js
{
    "cSpell.enableFiletypes": [
        "!javascript"
    ]
}
```

<img width="1187" alt="image" src="https://user-images.githubusercontent.com/3740137/211143727-4813f2be-e230-420c-b68c-bdb8d6315e27.png">



This extension uses [cspell](https://www.npmjs.com/package/cspell) to do the checking. If you are using cspell as part of your CI/CD process, then I suggest using a `cspell.config.yaml` file instead of putting things in VS Code's `settings.json`

All the `cspell` settings are availabe in VS Code `settings.json` with a `cSpell.` prefix. But VS Code settings overwrites arrays, making it difficult to set things at the Workspace level and then adjusting it at the folder level. 

CSpell has a lot of options to control how you want things checked.

```yaml
$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
---
$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
ignorePaths:
  - "node_modules"
# Overrides are processed in order
overrides:
  - filename: "**/*.{js,jsx}" # if it matches against the path
    # apply these settings
    enable: false # turn off spell checking
  - filename: "**/webpage/examples/**/*.{js,jsx}"
    # turn it back on
    enable: true
  - filename: "**/i18n/ru/**"
    language: ru

languageSettings:
  - languageId: javascript # if the file type matches
    # apply settings
    dictionaries: ["our_javascript_terms"]

# this only applies to the VS Code Extension
enableFiletype:
  - kotlin
  - "!json"
```

**Comment by brendan8c** [comment]
If you use this setting in the `settings.json` file
`   "cSpell.enableFiletypes": ["!javascript", "!jsonc"],`
Then spell checking is turned off completely in these files.
It is necessary for me that spelling would not be checked leash in the code.
I use this plugin for spell checking in code comments and nothing else.

**Comment by Jason3S** [comment]
@brendan8c,

It turns it completely off.

To check parts of a document, it is possible to use Regular Expression to include/exclude the parts you are interested in.

Example:

**`cspell.config.yaml`**
```yaml
$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
patterns:
  - name: json-key
    pattern: >-
      /".*?":/g
languageSettings:
  - languageId:
      - javascript
    includeRegExpList:
      - string
      - CStyleComment
  - languageId: json,jsonc
    ignoreRegExpList:
      - json-key
```

`npx cspell check webpack.config.js`

<img width="881" alt="image" src="https://user-images.githubusercontent.com/3740137/211153622-24fa6f83-ef70-4aba-9a9b-42196a348b5f.png">

`npx cspell check package.json`

<img width="531" alt="image" src="https://user-images.githubusercontent.com/3740137/211153651-6d9e8fe3-c9d3-4cd8-af8e-d87f74ad6373.png">

> **Note**
> `string` and `CStyleComment` are predefined patterns.
